env:
  browser: yes
extends: 'eslint:recommended'
globals:
  dat: no
  Phaser: no
rules:
  comma-spacing:
    - error
  linebreak-style:
    - error
    - unix
  no-shadow:
    - error
  semi:
    - error
    - always

